version = 1
SPDX-PackageName = "webcomp-carsharing"
SPDX-PackageSupplier = "(c) NOI Techpark <digital@noi.bz.it>"
SPDX-PackageDownloadLocation = "https://github.com/noi-techpark/webcomp-carsharing"

[[annotations]]
path = [".github/**", "infrastructure/**", ".gitignore", ".pre-commit-config.yaml", "LICENSE.md", ".editorconfig", ".env.example", "**.png", "**.json", "**.svg"]
precedence = "aggregate"
SPDX-FileCopyrightText = "(c) NOI Techpark <digital@noi.bz.it>"
SPDX-License-Identifier = "CC0-1.0"
