name: CI/CD

on:
  push:
  pull_request:

env:
  NODE_VERSION: 16.x

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: noi-techpark/github-actions/npm-build@v2
        with:
          build-command: npm run build
          node-version: ${{env.NODE_VERSION}}

      - name: REUSE Compliance Check
        uses: fsfe/reuse-action@v1

  deploy-test:
    runs-on: ubuntu-20.04
    if: github.ref == 'refs/heads/main'
    needs: test
    concurrency: deploy-test
    steps:
      - uses: actions/checkout@v2

      - uses: noi-techpark/github-actions/npm-build@v2
        with:
          build-command: npm run build
          node-version: ${{env.NODE_VERSION}}

      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          cache: 'pip'
          cache-dependency-path: '**/requirements.txt'

      
      - name: Post webcomponent to store
        env:
          CLIENT_SECRET: ${{secrets.KEYCLOAK_CLIENT_SECRET}}
        run: |
          pip install -r webcompstore-cli/requirements.txt
          python3 webcompstore-cli/webcompstore-cli.py --push main
      